version: '3.8'

services:
  # Base de données PostgreSQL (données principales)
  postgres:
    image: postgres:15
    container_name: ecommerce-postgres
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # Base de données MongoDB (recherche et cache)
  mongodb:
    image: mongo:7.0
    container_name: ecommerce-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

  # Base de données Redis pour les sessions et cache
  redis:
    image: redis:7.2-alpine
    container_name: ecommerce-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce-network

  # API Backend NodeJS
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - FRONTEND_URL=http://localhost:5173
      - BACKEND_URL=http://localhost:4000
      # --- Production (à commenter en local) ---
      # - FRONTEND_URL=http://162.19.78.55:8002
      # - BACKEND_URL=http://162.19.78.55:8001
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads 
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - ecommerce-network
    command: npm run dev

  # Frontend VueJS
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000/api
      - VITE_STRIPE_PUBLIC_KEY=pk_test_your_stripe_public_key
      # --- Production (à commenter en local) ---
      # - VITE_API_URL=http://162.19.78.55:8001/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - ecommerce-network
    command: npm run dev

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  backend_uploads:  # Volume pour les uploads

networks:
  ecommerce-network:
    driver: bridge
